/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import connection.Main;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Fernando
 */
public class ChatPrivado extends javax.swing.JFrame {
    int x,y;
    
    String destinatario;
    
    /**
     * Creates new form ChatPrivado
     */
    public ChatPrivado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public ChatPrivado(String destinatario) {
        this.setTitle("RolOnline - Chat con " + destinatario);
        this.destinatario = destinatario;
        initComponents();
        
        jTextFieldEnviar.requestFocus();
        
        jTextAreaChat.setLineWrap(true);
        jTextAreaChat.setWrapStyleWord(true);
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        jLabelNombre.setText(destinatario);
    }
    
    public Image getIconImage () {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEnviar = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jLabelChatPrivadoCon = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();
        jButtonEnviar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RolOnline - Chat");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnviarActionPerformed(evt);
            }
        });
        jTextFieldEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEnviarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 350, 20));

        jButtonSalir.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Cerrar");
        jButtonSalir.setFocusable(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabelChatPrivadoCon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelChatPrivadoCon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChatPrivadoCon.setText("Chat privado con: ");
        getContentPane().add(jLabelChatPrivadoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 210, 40));

        jScrollPane1.setFocusable(false);

        jTextAreaChat.setEditable(false);
        jTextAreaChat.setColumns(20);
        jTextAreaChat.setRows(5);
        jTextAreaChat.setText("Advertencia: Cuidado con lo que escribes,el servidor puede leerlo\n");
        jScrollPane1.setViewportView(jTextAreaChat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 440, 220));

        jButtonEnviar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEnviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg.jpg"))); // NOI18N
        jLabelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseDragged(evt);
            }
        });
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelFondoMousePressed(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // Guardamos el texto de la conversación actual
        Main.usuarioChat.put(destinatario, jTextAreaChat.getText());
        // Quitamos el chat de las ventanas abiertas
        Main.ventanasChatAbiertas.remove(destinatario);
        // Cerramos la ventana
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnviarActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // Si pulsamos el boton enviar
        enviar();
        jTextFieldEnviar.setText("");
        jTextFieldEnviar.requestFocus();
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jLabelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMousePressed
        x = evt.getX (); 
        y = evt.getY(); 
    }//GEN-LAST:event_jLabelFondoMousePressed

    private void jLabelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y); 
    }//GEN-LAST:event_jLabelFondoMouseDragged

    private void jTextFieldEnviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnviarKeyPressed
        if (evt.VK_ENTER == evt.getKeyCode()) {
            enviar ();
            jTextFieldEnviar.setText("");
        }
    }//GEN-LAST:event_jTextFieldEnviarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatPrivado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatPrivado("Test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelChatPrivadoCon;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextField jTextFieldEnviar;
    // End of variables declaration//GEN-END:variables

    private void enviar() {
        Calendar calendario = new GregorianCalendar();
        String msg ="[" + calendario.get(Calendar.HOUR_OF_DAY) + ":" +
                    calendario.get(Calendar.MINUTE) + "] " +
                    Main.name + ": " +jTextFieldEnviar.getText();
        mostrarMsg (msg);
        
        Main.msgPrivateCliente(msg, Main.name, destinatario);
    }
    
    public void mostrarMsg(String msg) {
        jTextAreaChat.append(msg + '\n');
        //System.out.println(msg);
    }
    
    public void log (String msg) {
        jTextAreaChat.setText(msg);
    }
}
