/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import commons.GameObserver;
import connection.Main;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Fernando
 */
public class Interfaz extends javax.swing.JFrame implements GameObserver {
    int x, y;
    String name;

    public Interfaz(String text) {
        this.name = text;
        Main.name = text;
        initComponents();
        this.version.setText(Main.version);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        jTextFieldEnviar.requestFocus();
        
        jTextAreaChat.setLineWrap(true);
        jTextAreaChat.setWrapStyleWord(true);
        
        DefaultCaret caret = (DefaultCaret) jTextAreaChat.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }
    
    public void cargarJugadores () {
        //Crear un objeto DefaultListModel
        DefaultListModel listModel = new DefaultListModel();
        //Recorrer el contenido del ArrayList
        for(int i=0; i<Main.jugadores.size(); i++) {
            //Añadir cada elemento del ArrayList en el modelo de la lista
            listModel.add(i, Main.jugadores.get(i));
        }
        //Asociar el modelo de lista al JList
        jListJugadores.setModel(listModel);
    }
    
    public Image getIconImage () {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jPanelDibujar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();
        jTextFieldEnviar = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jLabelChat = new javax.swing.JLabel();
        jPanelDados = new javax.swing.JPanel();
        jLabelDados = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelDe = new javax.swing.JLabel();
        jTextFieldDIni = new javax.swing.JTextField();
        jLabelA = new javax.swing.JLabel();
        jTextFieldDFin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        version = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListJugadores = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RolOnline - Principal");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jPanelDibujar.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanelDibujar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 480, 260));

        jTextAreaChat.setEditable(false);
        jTextAreaChat.setColumns(20);
        jTextAreaChat.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaChat.setRows(5);
        jTextAreaChat.setOpaque(false);
        jTextAreaChat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextAreaChatCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaChat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 480, 130));

        jTextFieldEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnviarActionPerformed(evt);
            }
        });
        jTextFieldEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEnviarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 390, -1));

        jButtonEnviar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEnviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jLabelChat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelChat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChat.setText("Chat:");
        getContentPane().add(jLabelChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jPanelDados.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDados.setOpaque(false);
        jPanelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDados.setText("Dados");
        jPanelDados.add(jLabelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 20));

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setText("Nº");
        jPanelDados.add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTextFieldNumero.setText("1");
        jPanelDados.add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 40, -1));

        jLabelDe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDe.setText("De");
        jPanelDados.add(jLabelDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextFieldDIni.setText("1");
        jPanelDados.add(jTextFieldDIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, -1));

        jLabelA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelA.setText("a");
        jPanelDados.add(jLabelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jTextFieldDFin.setText("6");
        jTextFieldDFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDFinActionPerformed(evt);
            }
        });
        jPanelDados.add(jTextFieldDFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 40, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tirar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelDados.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        getContentPane().add(jPanelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 230, 140));

        jButtonInfo.setBackground(new java.awt.Color(51, 51, 51));
        jButtonInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonInfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInfo.setText("Información");
        getContentPane().add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo3.png"))); // NOI18N
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 330, -1));

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sound.png"))); // NOI18N
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 40, 30));

        version.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        version.setForeground(new java.awt.Color(255, 255, 255));
        version.setEnabled(false);
        version.setFocusable(false);
        getContentPane().add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 200, 30));

        jListJugadores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jListJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListJugadoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListJugadores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 200, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jugadores:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFondo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg.jpg"))); // NOI18N
        jLabelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseDragged(evt);
            }
        });
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelFondoMousePressed(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 502));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        int ax = JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if(ax == JOptionPane.YES_OPTION) {
            if (!Main.desconectado) 
                Main.quit();
            else
                System.exit(0);
        }
//        else if(ax == JOptionPane.NO_OPTION)
//            JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        enviar (jTextFieldEnviar.getText());
        jTextFieldEnviar.setText("");
        jTextFieldEnviar.requestFocus();
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jTextFieldDFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDFinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int num = Integer.parseInt (jTextFieldNumero.getText());
            int de  = Integer.parseInt(jTextFieldDIni.getText());
            int a   = Integer.parseInt(jTextFieldDFin.getText());
            
            StringBuffer resultados = new StringBuffer();
            
            for (int i = 0; i < num; i++) {
                resultados.append((int)(Math.random()*a + de));
                resultados.append (" ");
            }
            // Mostramos el resultado en el chat de todos
            enviarDados(resultados, num, de, a);
        }
        catch (NumberFormatException ex) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void enviarDados (StringBuffer resultados, int casos, int ini, int fin) {      
        Calendar calendario = new GregorianCalendar();
         Main.msgCliente("[" + calendario.get(Calendar.HOUR_OF_DAY) + ":" +
                    calendario.get(Calendar.MINUTE) + "] Dados de " +
                    name + " (del " + ini + " al " + fin + "): " +
                    resultados.toString());
    }
    
    private void enviar(String msg) {
        if (msg.length() > 0) {
            Calendar calendario = new GregorianCalendar();
            Main.msgCliente("[" + calendario.get(Calendar.HOUR_OF_DAY) + ":" +
                    calendario.get(Calendar.MINUTE) + "] " +
                    name + ": " + msg);
        }
    }
    
    private void jTextFieldEnviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnviarKeyPressed
        if (evt.VK_ENTER == evt.getKeyCode()) {
            enviar (jTextFieldEnviar.getText());
            jTextFieldEnviar.setText("");
        }
    }//GEN-LAST:event_jTextFieldEnviarKeyPressed

    private void jTextAreaChatCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextAreaChatCaretUpdate
        
    }//GEN-LAST:event_jTextAreaChatCaretUpdate

    private void jLabelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMousePressed
        x = evt.getX ();
        y = evt.getY();
    }//GEN-LAST:event_jLabelFondoMousePressed

    private void jLabelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoMouseClicked

    private void jLabelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabelFondoMouseDragged

    private void jListJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListJugadoresMouseClicked
        // Si hacemos doble click
        if (evt.getClickCount() > 1) {
            new Thread () {
                public void run() {
                    if (Main.perfil != null)
                        Main.perfil.dispose();
                    
                    if (!jListJugadores.getSelectedValue().equals(name)) {
                        Main.perfil = new Perfil(jListJugadores.getSelectedValue());
                        Main.perfil.setVisible(true);
                    }
                    else {
                        // Abrimos la ventana de interfaz propia
                        throw new UnsupportedOperationException("Not supported yet.");
                    }
                    //while (Main.client == null) {}
                    //Main.darNombreCliente(jTextField1.getText());
                }
            }.start();
        }
    }//GEN-LAST:event_jListJugadoresMouseClicked

    private void jTextFieldEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnviarActionPerformed

    public void mostrarMsg(String msg) {
        jTextAreaChat.append(msg + '\n');
        //System.out.println(msg);
    }
    
    public void mostrarNewClient (String msg) {
        Calendar calendario = new GregorianCalendar();
        jTextAreaChat.append("[" + calendario.get(Calendar.HOUR_OF_DAY) + ":" +
                calendario.get(Calendar.MINUTE) + "] " +
                "Se ha conectado " + msg + '\n');
        
        Main.jugadores.add(name);
        cargarJugadores();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz("Test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelChat;
    private javax.swing.JLabel jLabelDados;
    private javax.swing.JLabel jLabelDe;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JList<String> jListJugadores;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JPanel jPanelDibujar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextField jTextFieldDFin;
    private javax.swing.JTextField jTextFieldDIni;
    private javax.swing.JTextField jTextFieldEnviar;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onGameStart() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onGameOver() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onError(String msg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onMsg(String msg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onChangeArea() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onNewClient(String msg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onPrivateMsg(String msg, String emisor, String destinatario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onDisconnectClient(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
