/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import connection.Main;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Fernando
 */
public class Perfil extends javax.swing.JFrame {
    int x,y;
    String name;
    
    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
    }
    
    public Perfil (String name) {
        initComponents();
        this.name = name;
        jLabelNombre.setText(name);
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public Image getIconImage () {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFicha = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jLabelPerfil = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jButtonEnviarMsg = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RolOnline - Perfil");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelFichaLayout = new javax.swing.GroupLayout(jPanelFicha);
        jPanelFicha.setLayout(jPanelFichaLayout);
        jPanelFichaLayout.setHorizontalGroup(
            jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanelFichaLayout.setVerticalGroup(
            jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 290, 380));

        jButtonSalir.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Cerrar");
        jButtonSalir.setFocusable(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabelInfo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setText("Ficha del personaje");
        getContentPane().add(jLabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabelPerfil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfil.setText("Perfil de: ");
        getContentPane().add(jLabelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, 20));

        jButtonEnviarMsg.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEnviarMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEnviarMsg.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviarMsg.setText("Enviar Mensaje Privado");
        jButtonEnviarMsg.setFocusable(false);
        jButtonEnviarMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarMsgActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviarMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg.jpg"))); // NOI18N
        jLabelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseDragged(evt);
            }
        });
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelFondoMousePressed(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarMsgActionPerformed
        new Thread () {
                public void run() {
                    // Si no esta ya abierta la ventana
                    if (!Main.ventanasChatAbiertas.containsKey(name)) {
                        // La abro
                        
                        // Lo añado a la lista de ventanas abiertas
                        Main.ventanasChatAbiertas.put(name, new ChatPrivado(name));
                        // Cogemos toda la conversación guardada (si existe)
                        if (Main.usuarioChat.containsKey(name)) {
                            Main.ventanasChatAbiertas.get(name).log(Main.usuarioChat.get(name));
                        }
                    }
                }
        }.start();
    }//GEN-LAST:event_jButtonEnviarMsgActionPerformed

    private void jLabelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoMouseClicked

    private void jLabelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMousePressed
        x = evt.getX ();
        y = evt.getY();
    }//GEN-LAST:event_jLabelFondoMousePressed

    private void jLabelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabelFondoMouseDragged

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarMsg;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPerfil;
    private javax.swing.JPanel jPanelFicha;
    // End of variables declaration//GEN-END:variables
}
