/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import connection.Main;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class Server extends javax.swing.JFrame {
    int x,y;
    
    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public Image getIconImage () {
        return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInfo = new javax.swing.JTextArea();
        jTextFieldEnviar = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jButtonStopServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonMin = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RolOnline - Panel del Servidor");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPaneInfo.setEditable(false);
        jTextPaneInfo.setColumns(20);
        jTextPaneInfo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextPaneInfo.setRows(5);
        jTextPaneInfo.setFocusable(false);
        jScrollPane1.setViewportView(jTextPaneInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 460, 230));

        jTextFieldEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnviarActionPerformed(evt);
            }
        });
        jTextFieldEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEnviarKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 370, 20));

        jButtonEnviar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEnviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.setFocusable(false);
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, 20));

        jButtonStopServer.setBackground(new java.awt.Color(51, 51, 51));
        jButtonStopServer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonStopServer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStopServer.setText("Cerrar Servidor");
        jButtonStopServer.setFocusable(false);
        jButtonStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopServerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStopServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Información del Servidor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jButtonMin.setBackground(new java.awt.Color(51, 51, 51));
        jButtonMin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMin.setText("_");
        jButtonMin.setFocusable(false);
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg.jpg"))); // NOI18N
        jLabelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseDragged(evt);
            }
        });
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelFondoMousePressed(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 529, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        enviar (jTextFieldEnviar.getText());
        jTextFieldEnviar.setText("");
    }//GEN-LAST:event_jButtonEnviarActionPerformed
    
    private void enviar(String msg) {
        if (msg.length() > 0) {
            Calendar calendario = new GregorianCalendar();
            Main.respuestaMsg("[" + calendario.get(Calendar.HOUR_OF_DAY) + ":" +
                    calendario.get(Calendar.MINUTE) + "] " +
                    "Server" + ": " + msg);
        }
    }
    
    private void jTextFieldEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnviarActionPerformed

    private void jLabelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMousePressed
        x = evt.getX (); 
        y = evt.getY();
    }//GEN-LAST:event_jLabelFondoMousePressed

    private void jLabelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        
        setLocation(point.x - x, point.y - y); 
    }//GEN-LAST:event_jLabelFondoMouseDragged

    private void jButtonStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopServerActionPerformed
        int ax = JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas"
                + " cerrar el servidor?\n Expulsará a todos los usuarios", "Cerrar Servidor", JOptionPane.YES_NO_OPTION);
        if(ax == JOptionPane.YES_OPTION) {
            Main.servidor.desconectarClientes();
            Main.servidor.pararServidor();
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonStopServerActionPerformed

    private void jTextFieldEnviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnviarKeyPressed
        if (evt.VK_ENTER == evt.getKeyCode()) {
            enviar (jTextFieldEnviar.getText());
            jTextFieldEnviar.setText("");
        }
    }//GEN-LAST:event_jTextFieldEnviarKeyPressed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        setExtendedState(Server.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_jButtonMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }
    
    public javax.swing.JTextArea cogerInfo(){
        return jTextPaneInfo;
    }
    
    public void guardarInfo(javax.swing.JTextArea area){
        jTextPaneInfo = area;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonStopServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEnviar;
    private javax.swing.JTextArea jTextPaneInfo;
    // End of variables declaration//GEN-END:variables
}
